apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: a-python-library
  namespace: default
  annotations:
    backstage.io/techdocs-ref: dir:.
spec:
  type: service
  lifecycle: experimental
  owner: john@example.com
