apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: service-with-docs
  description: The place to be
  # namespace: default  # Essayez de commenter cette ligne
  annotations:
    backstage.io/techdocs-ref: dir:.
spec:
  type: service
  lifecycle: experimental
  owner: john@example.com
